### ISSUE TITLE
Auto-fixing code not correclty checking if it should run

### ISSUE THREAD

**Issue by gsherwood** [cakephp/cakephp-codesniffer#102]
The auto fixes in the standard don't check if they are supposed to run, so they will run even if the list of sniffs is being filtered with the `--sniffs` command line argument.

Examples of the code that needs correcting are:
https://github.com/cakephp/cakephp-codesniffer/blob/phpcs-fixer/Sniffs/ControlStructures/ElseIfDeclarationSniff.php#L53
https://github.com/cakephp/cakephp-codesniffer/blob/phpcs-fixer/Sniffs/PHP/DisallowShortOpenTagSniff.php#L58

The change is fairly easy. Instead of:
````php
$phpcsFile->addFixableError($error, $stackPtr, 'MessageCode');
if ($phpcsFile->fixer->enabled === true) {
    // Fixer code here.
}
````

You would write:
````php
$fix = $phpcsFile->addFixableError($error, $stackPtr, 'NotAllowed');
if ($fix === true) {
    // Fixer code here.
}
````

The `addFixableError()` and `addFixableWarning()` methods will only return TRUE is the fixer is enabled and if the message is not being filtered out in some way.

**Comment by antograssiot** [comment]
this has been done a while ago.
