### ISSUE TITLE
Underscore conflict on protected methods

### ISSUE THREAD

**Issue by greenmanspirit** [cakephp/cakephp-codesniffer#121]
Hello,

It appears that we have sniffs wanting opposite things.

The following sniff wants you to have an underscore in front of protected method names:
CakePHP.NamingConventions.ValidFunctionName.ProtectedNoUnderscore

The following sniffs want you to -not- have an underscore in front of protected method names:
PEAR.NamingConventions.ValidFunctionName.PublicUnderscore
Squiz.NamingConventions.ValidFunctionName.PublicUnderscore

**Comment by ADmad** [comment]
We have [passing](https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/tests/files/class_underscore_prefix_pass.php) tests file showing no errors are reported for methods with underscore prefix.

**Comment by bcrowe** [comment]
We have the "no underscore" sniffs marked as excluded for the time being because we've bounced around the idea of removing the underscore prefixes in a future version.

But, until then, we'll be requiring underscores for protected methods.

**Comment by ADmad** [comment]
I'll check with latest phpcs and skip the reported sniffs if they are indeed causing problem.

**Comment by greenmanspirit** [comment]
We worked it out in the IRC. I had been trying to verify 2.x code against the master branch.  When I read it, I thought that the 1.x releases were for 1.x versions of cakephp. I am good now.

**Comment by btaens** [comment]
This causes problems for PhpStorm's phpcs integration. If I write them with an underscore, it says it mustn't be with an underscore. If I don't, it says the opposite.

**Comment by deizel** [comment]
I have the same problem with this one particular rule, even though it works fine on the command line.

Doesn't seem to be related to any IDE settings I can find, but it happens in both PhpStorm 9 and EAP.

**Comment by deizel** [comment]
Seem to be an issue with PhpStorm: [WI-17740](https://youtrack.jetbrains.com/issue/WI-17740#comment=27-1029374)
