### ISSUE TITLE
Codesniffer 1.0.0 passed cakephp 2.x functions and variables with underscore

### ISSUE THREAD

**Issue by greenmanspirit** [cakephp/cakephp-codesniffer#122]
I am using codesniffer 1.0.0 and I had two function names in my controllers pass with underscores. The first was "public function update_children" and the second was "public function get_needed_fields". It is also passing with $title_for_layout still in app/Controller/PagesController.php.

**Comment by jadb** [comment]
@greenmanspirit - this is to be expected on the 1.0 version. If you are trying to run it for a cake3 project, use the 2.0 version.

**Comment by greenmanspirit** [comment]
This is for a cakephp 2.x project. I submitted this because the cakephp coding standard here http://book.cakephp.org/2.0/en/contributing/cakephp-coding-conventions.html#naming-convention say that both of those situations are invalid.

**Comment by jadb** [comment]
@greenmanspirit in general, its advised to use camelBacked method names. However, in cake2, action names in the controller could be using underscores.

**Comment by ADmad** [comment]
Controllers are allowed to have method name with underscore.

**Comment by greenmanspirit** [comment]
Ok, I must have misread. Thank you.
