### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp-codesniffer#125]
I think that the 1.0.0 needs some brief release notes to outline that is it the version to use for CakePHP2. Currently it's just got a commit message, when some more verbose notes could be given to better help users still working on 2.x content.

https://github.com/cakephp/cakephp-codesniffer/releases/tag/1.0.0

**Comment by markstory** [comment]
I can take care of this.

**Comment by davidyell** [comment]
Thanks Mark :smile:

**Comment by markstory** [comment]
Done. If there are other things you'd like to see in the notes let me know.
