### ISSUE TITLE
Function with yield throws 'Function return type is not void, but function has no return statement'

### ISSUE THREAD

**Issue by Marlinc** [cakephp/cakephp-codesniffer#152]
A function using yield returns "Function return type is not void, but function has no return statement" as error when `\Generator` has been defined as `@return`.

I tried to apply squizlabs/PHP_CodeSniffer@591d44bd23f02a88354be515c0bb35f3f975fe33 which fixed the issue. So this would be the same issue as squizlabs/PHP_CodeSniffer#479.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
