### ISSUE TITLE
Check for whitespace on empty/blank lines

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp-codesniffer#166]
The [PSR2 ruleset](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR2/ruleset.xml#L39) has made the whitespace checks provided by `Squiz.WhiteSpace.SuperfluousWhitespace` a bit too lenient. We should bump up the severity of those checks again in our ruleset, especially the check for whitespace on blank lines.

**Comment by dereuromark** [comment]
Any trailing whitespace imo.

**Comment by ADmad** [comment]
Trailing spaces on code lines are already being checked. Just for blank lines it's skipped.

**Comment by antograssiot** [comment]
closing as #167 is open now
