### ISSUE TITLE
Consistency rule for tailing array element commas

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp-codesniffer#168]
Ref: https://github.com/cakephp/migrations/pull/260/files/79532cca6022f56c80eca4f317f961f8bab6b4c1#r77485760 and @dereuromark 

IMHO it is beneficial to always omit it because else you would be required to do, like so

```php
$this->find('all', ['options' => $options,]);
```

However when having multiple lines its beneficial to always add because then you never forget to add to prior items, like so:

```php
->add($this->aliasField('username'), 'Search.Like', [
    'before' => true,
    'after' => true,
]);
```

### Suggestions

* A.) Never a tailing comma
* B.) Never a tailing comma on inline-use, always a tailing comma on block-use
* C.) Always a tailing comma

**Comment by ravage84** [comment]
I prefer B.

Using them inline looks odd and I see no benefit from using them.
But using them "on block-use", makes copying and editing a line in a multiple line array a breeze.

**Comment by dereuromark** [comment]
B is the Standard usually

**Comment by markstory** [comment]
I do B as well.

**Comment by antograssiot** [comment]
for instance cakephp/migrations doesn't use this standard but psr-2 only.
@inoas would you like to submit a PR ??

**Comment by dereuromark** [comment]
Cake was always more specifically than psr2.

**Comment by ADmad** [comment]
B for me too.

**Comment by inoas** [comment]
@antograssiot Can't do it anytime soon. If no one picks it up I can take a look early next year.

**Comment by lorenzo** [comment]
I'll vote A, we are making it harder and harder to contribute to cake for no good reason.

**Comment by dereuromark** [comment]
And how does A help here? :smiley_cat:

**Comment by ADmad** [comment]
We should either go for B or maintain status quo :)

**Comment by inoas** [comment]
A) and B) both make kind of sense *to me*. 

I do also understand @lorenzo argument. However the trailing commata will not be the issue someone will have in his face but rather the whole contribution work flow, unit tests etc, IMHO.

**Comment by dereuromark** [comment]
And as long as it is an auto-fixer, there is no overhead involved, as it will be fixed for you, you dont have to wry about it.

**Comment by markstory** [comment]
Do we need to standardize trailing commas at all?

**Comment by ravage84** [comment]
Sure, if we want to brag about consistency? :smirk_cat:

**Comment by lorenzo** [comment]
Sorry, I meant A as no changes required. I don't think we need to make this an standard.

**Comment by dakota** [comment]
I don't think we need to make any changes as @lorenzo said.

**Comment by antograssiot** [comment]
also ok to keep it as is. At least I'm not against B but won't work on it

**Comment by inoas** [comment]
We can just agree on doing A xor B :P "most of the time" and put it in the code styleguides in the book? No need to "fix" existing styles.

**Comment by ADmad** [comment]
Putting style guides in doc that are not actually enforced doesn't make much sense.

Closing the issue.

**Comment by dereuromark** [comment]
Someone can just port my created https://github.com/spryker/code-sniffer/compare/feature/trailing-comma  ArrayDeclarationSniff - and problem is solved :)

- Single-line: no trailing comma
- Multi-line: trailing comma

Both auto-fixed for everyones convenience.
