### ISSUE TITLE
Using functions from cake should require the relative components

### ISSUE THREAD

**Issue by gmponos** [cakephp/cakephp-codesniffer#183]
I know that this package is supposed to be a collection of rules for `CakePHP` but someone might find it useful and might want to use at his own code/project which might not be in CakePHP.

At this [line](https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/Sniffs/NamingConventions/ValidVariableNameSniff.php#L175) you are using a function from cakephp but you are not requiring the related package inside composer.

**Comment by markstory** [comment]
I'm reluctant to add a dependency on cakephp/utility for a single function. It might be simpler to duplicate the function into the fixer.
