### ISSUE TITLE
Upgrade to support CodeSniffer 3.0

### ISSUE THREAD

**Issue by dakota** [cakephp/cakephp-codesniffer#186]
Squizlabs just released [version 3.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0) of CodeSniffer. We should upgrade our sniffs as per the [migration guide](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide)

**Comment by ADmad** [comment]
@antograssiot already has a branch using CS v3 ready https://github.com/cakephp/cakephp-codesniffer/tree/3.0 :smile:

**Comment by ADmad** [comment]
Closing as PR #187 is open.
