### ISSUE TITLE
[question] Why the variable name can be only camel cased ?

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp-codesniffer#190]
Hi,

I'm using the cakephp codesniffer, sometimes i need to have another case for variable name especially with `compact(...)`, for eg.:
```php
$my_table_field = 'a value';
$another_table_field = 'another value';

$this->MyTable->newEntity(compact('my_table_field', 'another_table_field'));
```
I want just to know why we can use only the camel cased.

Thanks

**Comment by lorenzo** [comment]
That's the standard we chose for CakePHP.

As with any styling standard, it is just a matter of personal preferences, or cultural reasons.

Since we want everyone coding for the CakePHP core to use the same coding standard, then we allow only one style.

**Comment by dereuromark** [comment]
As for your issue: Just use an array directly instead of single vars and you will be fine. Problem solved with probably even less lines of code.

**Comment by flashios09** [comment]
@dereuromark i know how to solve it, my question was **why** not **how**.

It's a personal convention, i use the snake case for **table field name** vars, like this i can easily distinguish them.
```php
$myVar = 'a value';
$created_at = 'i know this is a var that correspond to the created_at table field'; 
```

**Comment by lorenzo** [comment]
@flashios09 you are not forced to use this coding standard, though. You can also modify it , so that it allows both types of variables

**Comment by flashios09** [comment]
@lorenzo is it possible to have a custom config like with **eslint** or i have to fork this repo ?

**Comment by markstory** [comment]
You can use a phpcs config file to import the cakephp rules, exclude the ones you don't like and add your own sniffs/rules.

**Comment by flashios09** [comment]
@markstory thanks, i created a **phpcs.xml.dist** file at the root of my project and it works

```xml
<?xml version="1.0"?>
<ruleset name="MyCakePHP">
  <description>MyCakePHP coding standard</description>

  <rule ref="CakePHP"/>

  <rule ref="Zend.NamingConventions.ValidVariableName.StringVarNotCamelCaps">
    <severity>0</severity>
  </rule>

</ruleset>
```
