### ISSUE TITLE
Bug: Leading operators in multiline not allowed

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp-codesniffer#198]
```
ERROR | Expected 1 space before ., but 12 found
```

For
```php
$expected = 'bar'
    . 'foo';
```

This is cleaner than 
```php
$expected = 'bar' . 
    'foo';
```

as it shows the concat operator more clearly and should be allowed IMO

**Comment by ravage84** [comment]
I'm OK with both variations but for once I would not enforce one over the other. Thus I vote for just fixing the bug but nothing more.

**Comment by othercorey** [comment]
You can set ignoreNewlines to true if you have Whitespace.OperatorSpacing enabled.

**Comment by dereuromark** [comment]
Are we doing that now for our sniffer?

**Comment by dereuromark** [comment]
Doesnt look like it: https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/ruleset.xml#L125

**Comment by othercorey** [comment]
That is the LogicalOperatorSpacing. I don't see the regular operator spacing enabled.

**Comment by dereuromark** [comment]
I am fairly certain this default sniffer ruleset had the issue though with code I commited.
