### ISSUE TITLE
vscode support

### ISSUE THREAD

**Issue by waspinator** [cakephp/cakephp-codesniffer#210]
Thanks for adding cakephp support to phpcs. 

I'm trying to get vscode with the [phpcs plugin](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs) working with cakephp.

---

Looking at it now, it seems that vscode does understand `.ctp` files and marks them as `.php`, but I was expecting code to reformat to some php or cakephp standard. Is that a thing?

I have `"editor.formatOnSave": true,` set in my user settings.

Thanks

**Comment by markstory** [comment]
Did you setup your default standard as per the documentation for the phpcs plugin in vscode?

(disclaimer: I don't use vscode and won't be much further help on this).
