### ISSUE TITLE
Special treating of 'use function', 'use const'

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp-codesniffer#214]
I have the following code:

```php
use Cake\ORM\Exception\PersistenceFailedException;
use Cake\Utility\Security;
use Exception;
use RuntimeException;
use function compact;
```

When I check the code with codesniffer I get the following message:
```
 12 | ERROR | Use classes must be in alphabetical order. Was
    |       | expecting functioncompact
```
It expects the code to be:
```php
use Cake\ORM\Exception\PersistenceFailedException;
use Cake\Utility\Security;
use Exception;
use function compact;
use RuntimeException;
```

Which is kind of unnatural.

I would like to see `use function` and `use const` blocks after classes imports.

**Comment by dereuromark** [comment]
I wonder what https://github.com/slevomat/coding-standard does in this case.

**Comment by dereuromark** [comment]
Do we want to use the proper one instead then?

**Comment by nojimage** [comment]
I think needs to solve this problem, for PSR-12.

PSR-12: Extended Coding Style - PHP-FIG https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements
