### ISSUE TITLE
Adding more useful sniffs for "next"

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp-codesniffer#226]
I compared the standard with the Spryker one and want to point out a few missing ones that could be useful before we declare a more stable release here:

- [ ] ~~PEAR.Classes.ClassDeclaration~~
- [ ] ~~PEAR.ControlStructures.ControlSignature~~
- [ ] ~~Zend.Files.ClosingTag~~

- [x] SlevomatCodingStandard.Commenting.DisallowOneLinePropertyDocComment
- [x] SlevomatCodingStandard.Commenting.EmptyComment
- [x] SlevomatCodingStandard.ControlStructures.DisallowContinueWithoutIntegerOperandInSwitch
- [x] SlevomatCodingStandard.Namespaces.UseSpacing
- [x] SlevomatCodingStandard.PHP.ShortList
- [x] SlevomatCodingStandard.Variables.DuplicateAssignmentToVariable

and also some of the Spryker ones, especially for docblocks.

**Comment by ADmad** [comment]
> PEAR.Classes.ClassDeclaration

Isn't `PSR2.Classes.ClassDeclaration` which is already used enough?

>  PEAR.ControlStructures.ControlSignature

Checking it's sniff I am not quite sure what it does but I think placements of braces for control structures should already be covered by PSR2 standards.

>  SlevomatCodingStandard.Commenting.DisallowOneLinePropertyDocComment

This sounds too pedantic.

>  SlevomatCodingStandard.Commenting.EmptyComment

Our custom `FunctionComment` sniff already covers reporting of empty comments/

>  SlevomatCodingStandard.ControlStructures.DisallowContinueWithoutIntegerOperandInSwitch

:+1:

>  SlevomatCodingStandard.Namespaces.UseSpacing

:+1:

> SlevomatCodingStandard.PHP.ShortList

:+1:, though would be a chore to remove all existing `list()` usage.

> SlevomatCodingStandard.Variables.DuplicateAssignmentToVariable

Not sure how this sniff works but if it complains about reassigning a method argument too then it's a bit too pedantic IMO.

>  Zend.Files.ClosingTag

Already covered by `PSR2.Files.ClosinTag.NotAllowed`.

**Comment by dereuromark** [comment]
> This sounds too pedantic.

Well, this is just normalizing it, preventing some IDEs to output the inline ones where they shouldnt

DuplicateAssignmentToVariable helps to prevent bugs by accidentally overwriting variables.
We can test if it affects current code of course.

**Comment by ADmad** [comment]
Closing as all seem to be checked off.
