### ISSUE TITLE
Next: code sniffer issue with stricttypes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp-codesniffer#229]
I think the codesniffer should not remove the whitespace between these lines ( https://github.com/cakephp/cakephp/pull/12950/commits/0aeceba35ce7df9e5508e68ea6e5be4c5c8a5c51 ).
They should be OK, or even added if not present IMO.

The license doc block can, but doesnt have to present for this to be in effect.

**Comment by ADmad** [comment]
The related sniff can be configured to add new line after the "declare" statement but then we would have new line above license docblocks too. Personally I am fine with that.

**Comment by dereuromark** [comment]
Yeah I am fine with that too.

But maybe the "use statements" should declare a line above instead? And the declare whitespace loosened.
This way the license block is kept this way, but the spacing otherwise might be fine?
