### ISSUE TITLE
Final proposals for 4.x standard

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp-codesniffer#239]
I will try to seep through the [Spryker sniffs](https://github.com/spryker/code-sniffer) for highest code quality and check which ones have the highest prio to be included in Cake sniffer.

- Spryker.Classes.MethodArgumentDefaultValue (might be in Slevomatik)
- Spryker.Classes.MethodDeclaration
- Spryker.Classes.MethodTypeHint
- Spryker.Classes.ReturnTypeHint
- Spryker.Commenting.DocBlock
- Spryker.Commenting.DocBlockNoInlineAlignment
- Spryker.Commenting.DocBlockParam
- Spryker.Commenting.DocBlockParamAllowDefaultValue
- Spryker.Commenting.DocBlockParamArray
- Spryker.Commenting.DocBlockParamNotJustNull
- Spryker.Commenting.DocBlockPipeSpacing
- Spryker.Commenting.DocBlockReturnNullableType
- Spryker.Commenting.DocBlockReturnSelf
- Spryker.Commenting.DocBlockReturnTag
- Spryker.Commenting.DocBlockReturnVoid
- Spryker.Commenting.DocBlockStructure
- ~~Spryker.Commenting.DocBlockTagGrouping~~ (too pedantic for Cake, too much noise changes)
- ~~Spryker.Commenting.DocBlockTagOrder~~ (too pedantic for Cake, too much noise changes)
- ~~Spryker.Commenting.DocBlockThrows~~ (too pedantic for Cake, too much noise changes)
- ~~Spryker.Commenting.DocBlockTypeOrder~~
- Spryker.Commenting.DocBlockVar
- Spryker.Commenting.DocBlockVarNotJustNull
- Spryker.Commenting.FullyQualifiedClassNameInDocBlock (might be in Slevomatik)
- Spryker.Commenting.InlineDocBlock (might be in Slevomatik)
- Spryker.ControlStructures.ConditionalExpressionOrder
- Spryker.ControlStructures.ControlStructureSpacing
- Spryker.ControlStructures.NoInlineAssignment
- Spryker.Formatting.ArrayDeclaration (might be in Slevomatik)
- Spryker.Namespaces.FunctionNamespace
- Spryker.Namespaces.UseStatement (might be in Slevomatik)
- Spryker.Namespaces.UseWithAliasing (might be partially in Slevomatik)
- Spryker.PHP.NoIsNull (might be in Cake)
- Spryker.PHP.PhpSapiConstant (might be in Cake)
- Spryker.PHP.PreferCastOverFunction (might be in Cake)
- Spryker.PHP.RemoveFunctionAlias (might be in Cake)
- Spryker.PHP.ShortCast (might be in Cake)
- Spryker.WhiteSpace.CommaSpacing (might be in Cake)
- Spryker.WhiteSpace.ConcatenationSpacing (might be in Cake)
- Spryker.WhiteSpace.DocBlockSpacing
- Spryker.WhiteSpace.EmptyEnclosingLine
- Spryker.WhiteSpace.EmptyLines
- Spryker.WhiteSpace.MemberVarSpacing
- Spryker.WhiteSpace.ObjectAttributeSpacing
- Spryker.WhiteSpace.OperatorSpacing (might be in Cake)
- [ ] Especially important: The new sniff/changes around $this chainable and to properly assert

Maybe someone can help out verifying which ones are useful to port/include and make a PR.

I will keep this list updated as to our progress (crossing out, accepting and merging etc)

**Comment by ADmad** [comment]
We should ensure not to go overboard with adding too many sniffs. Having too many could cause a noticeable delay/stutter when using IDE/editor plugins which check for CS errors as you type.

For e.g. checks for docblocks is something we can go easy on.

**Comment by dereuromark** [comment]
Yeah, it just helps to prevent human errors where they can easily be prevented.
Lets find the most useful and common issue fixers, and then find a good compromise here.

One important thing: Having xdebug disabled makes cs run 4-5x as fast, that will already take out the performance issue basically for most cases.

**Comment by dereuromark** [comment]
We are missing a quite basic sniff for spacing between (interface) methods:
https://github.com/cakephp/cakephp/pull/13223/files#diff-f615e67b9f687da027b935bbf938fd8eR281

**Comment by ADmad** [comment]
That's strange, I would expect the the sniffs provided by `PSR2` standard to take care of this.

**Comment by dereuromark** [comment]
A recent patch just now added this it seems :) Like a week ago or so.
At least now the spacing issue is resolved now.

**Comment by ADmad** [comment]
Good to know. Also since PSR12 is now accepted we can expect the `PSR12` ruleset in phpcs to be updated soon to adhere to all it's rules.

**Comment by ADmad** [comment]
I think this can be closed. The ruleset we have now is good enough. I have already merged `next` into `master` and it's ready for tagging.
