### ISSUE TITLE
`::class` construct is wrongly reported as a constant

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp-codesniffer#242]
In the code:
`$this->getMockBuilder(\Aws\S3\S3Client::class)`

Console output:
` 124 | ERROR | Constants must be uppercase; expected CLASS but found class`

Codesniffer v. 1.0.4

**Comment by dereuromark** [comment]
I am sure this is fixed in later versions of the repo.

**Comment by bancer** [comment]
Later versions cannot be used with Cake 2.x.

**Comment by dereuromark** [comment]
You can open a PR with the suggested backports.

**Comment by dereuromark** [comment]
Is there sth to be done here? People should be using 3.x of code sniffer by now.

**Comment by markstory** [comment]
I'm going to close it. If folks feel really strongly they can comment here and provide a working patch.
