### ISSUE TITLE
Update docs to show sniffer versions for framework versions

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp-codesniffer#253]
I think it would be beneficial to show in the documentation which versions of the sniffer are for which versions of the framework.

Now that the sniffer has 2.x and 3.x releases and 4.x betas, I'm unsure which version is for what framework release.

**Comment by dereuromark** [comment]
Can you make a PR here?

**Comment by davidyell** [comment]
Closing in favour of the open pull request.
