### ISSUE TITLE
Follow PSR-12 to the T?

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp-codesniffer#258]
[PSR-12](https://www.php-fig.org/psr/psr-12/) was finalized a while ago and new v3.5 of phpcs has been released with updated ruleset for it, which is included in our `next` ruleset used for Cake 4.

This has caused our core codebase to start generating few errors.

PSR-12 has some silly rules like requiring an empty line after the opening `<?php` tag, etc.

So question is whether we ignore such rules or update our code?

My opinion is not be pedantic about such things and simply update our codebase. It should be easy enough with automated fixers and shouldn't require any/too much manual work.

**Comment by markstory** [comment]
If there are automatic fixers for rules we can apply those. If there are pedantic rules that are going to create a bunch of manual work I'm less interested in applying those as its just a time sink.

**Comment by ADmad** [comment]
The only real concern is rule related to ordering of file header blocks. For e.g. PSR12 expect the file level block to be before the `declare()` statement.

The `FileHeader` sniff is currently buggy and doesn't handle auto fixing the ordering to blocks/statements. It hangs hangs on some files. So I have disabled it in #261.

We can revisit it once a new phpcs bugfix release is done.

**Comment by dereuromark** [comment]
I reported 3 more bugs. They released new sniffs in poor quality.

**Comment by ADmad** [comment]
We are now following all PSR-12 rules expect those related to ordering of file header blocks (as they can't be fixed automatically) and the one requires a blank line after opening PHP tag.
