### ISSUE TITLE
Conflict PSR-2 with PSR-12 rules

### ISSUE THREAD

**Issue by nojimage** [cakephp/cakephp-codesniffer#268]
I was writing a multi-line if statement like this:

```php
<?php

if ($expr1
    && $expr2) {
    // if body
}

```

This was fine for versions prior to 3.1.2.
However, when I updated to cakephp-codesniffer 3.2.0, I got a PSR-12 `PSR12.ControlStructures.ControlStructureSpacing.FirstExpressionLine` error.

So I modified the code as follows:

```php
<?php

if (
    $expr1
    && $expr2
) {
    // if body
}
```

However, this time a PSR-2 `PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace` error occurs.

I think there is a problem with PSR-12 and PSR-2 living together. Can I disable PSR-2?

CakePHP-CodeSniffer 3.2.0
PHP_CodeSniffer 3.5.2

**Comment by dereuromark** [comment]
From what I understand PSR-12 replaces PSR-2 where conflicting.
So yeah, the one in 2 can and probably should be disabled then.

**Comment by dereuromark** [comment]
This is now solved in master.
