### ISSUE TITLE
Allow @throw tags with {@inheritDoc)

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-codesniffer#294]
Sometimes a method is overridden just to add new error handling.

We could accept @throw tags if they are the only tag without requiring @param/@return tags.

API docs could check if an {@inheritDoc} block has only @throw tags and merge with the inherited docblock. This should be safe as @throw tags don't conflict with each other.

**Comment by markstory** [comment]
Seems like a good idea to me.
