### ISSUE TITLE
Should we allow {@inheritDoc} blocks with no tags?

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-codesniffer#295]
The current standard is:

-  `@inheritDoc` for docblocks that inherit everything
- {@inheritDoc} for docblocks that inherit the summary + description

These only count if they are the first line in the docblock.

Do we want to allow variations? This current standard allows us to override parameter types and return types for co-variance and contra-variance support in PHP.

We do not want to try and merge incomplete tags because they will conflict, and it will make both API docs and IDE interpretation difficult.

**Comment by markstory** [comment]
> Do we want to allow variations? This current standard allows us to override parameter types and return types for co-variance and contra-variance support in PHP.

We can/should use copy/paste for anything outside the scenarios you outlined. More complex scenarios justify repeating and refining the docs in my opinion.

**Comment by othercorey** [comment]
Sounds good for now.
