### ISSUE TITLE
Cannot install cakephp/cakephp-codesniffer on CakePHP 4.0.5

### ISSUE THREAD

**Issue by jmcd73** [cakephp/cakephp-codesniffer#296]
bin/cake version
4.0.5

php -v
PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies

# Problem with installation not sure how to resolve this
composer require --dev "cakephp/cakephp-codesniffer"
Using version ^4.1 for cakephp/cakephp-codesniffer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove phpstan/phpdoc-parser 0.4.3
    - Conclusion: don't install phpstan/phpdoc-parser 0.4.3
    - slevomat/coding-standard 6.0.0 requires phpstan/phpdoc-parser 0.3.5 - 0.4.0 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0].
    - slevomat/coding-standard 6.0.1 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.2 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.3 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.4 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.5 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.0.6 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.0.7 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.0.8 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.1.0 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.1.1 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - Can only install one of: phpstan/phpdoc-parser[0.3.5, 0.4.3].
    - Can only install one of: phpstan/phpdoc-parser[0.4.0, 0.4.3].
    - Can only install one of: phpstan/phpdoc-parser[0.4.1, 0.4.3].
    - Can only install one of: phpstan/phpdoc-parser[0.4.2, 0.4.3].
    - Installation request for phpstan/phpdoc-parser (locked at 0.4.3) -> satisfiable by phpstan/phpdoc-parser[0.4.3].
    - Installation request for cakephp/cakephp-codesniffer ^4.1 -> satisfiable by cakephp/cakephp-codesniffer[4.1.0].
    - Conclusion: don't install slevomat/coding-standard 6.2.0|install slevomat/coding-standard 6.0.0|install slevomat/coding-standard 6.0.1|install slevomat/coding-standard 6.0.2|install slevomat/coding-standard 6.0.3|install slevomat/coding-standard 6.0.4|install slevomat/coding-standard 6.0.5|install slevomat/coding-standard 6.0.6|install slevomat/coding-standard 6.0.7|install slevomat/coding-standard 6.0.8|install slevomat/coding-standard 6.1.0|install slevomat/coding-standard 6.1.1
    - Conclusion: remove slevomat/coding-standard 6.2.0|install slevomat/coding-standard 6.0.0|install slevomat/coding-standard 6.0.1|install slevomat/coding-standard 6.0.2|install slevomat/coding-standard 6.0.3|install slevomat/coding-standard 6.0.4|install slevomat/coding-standard 6.0.5|install slevomat/coding-standard 6.0.6|install slevomat/coding-standard 6.0.7|install slevomat/coding-standard 6.0.8|install slevomat/coding-standard 6.1.0|install slevomat/coding-standard 6.1.1
    - cakephp/cakephp-codesniffer 4.1.0 requires slevomat/coding-standard >=6.0 <6.2 -> satisfiable by slevomat/coding-standard[6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5].
    - Can only install one of: slevomat/coding-standard[6.1.2, 6.2.0].
    - Can only install one of: slevomat/coding-standard[6.1.3, 6.2.0].
    - Can only install one of: slevomat/coding-standard[6.1.4, 6.2.0].
    - Can only install one of: slevomat/coding-standard[6.1.5, 6.2.0].
    - Installation request for slevomat/coding-standard (locked at 6.2.0) -> satisfiable by slevomat/coding-standard[6.2.0].

**Comment by othercorey** [comment]
You seem to have other packages required in composer.json that conflict with cakephp-codesniffer. 

You don't provide enough information to explain more.

**Comment by jmcd73** [comment]
Sorry further detail

Install fresh CakePHP project
```
composer create-project --prefer-dist cakephp/app:4.* test-project
cd test-project
composer require --dev "cakephp/cakephp-codesniffer"
```

Output of `composer require --dev "cakephp/cakephp-codesniffer"`
```
Using version ^4.1 for cakephp/cakephp-codesniffer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove phpstan/phpdoc-parser 0.4.3
    - Conclusion: don't install phpstan/phpdoc-parser 0.4.3
    - slevomat/coding-standard 6.0.0 requires phpstan/phpdoc-parser 0.3.5 - 0.4.0 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0].
    - slevomat/coding-standard 6.0.1 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.2 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.3 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.4 requires phpstan/phpdoc-parser 0.3.5 - 0.4.1 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1].
    - slevomat/coding-standard 6.0.5 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.0.6 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.0.7 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.0.8 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.1.0 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - slevomat/coding-standard 6.1.1 requires phpstan/phpdoc-parser 0.3.5 - 0.4.2 -> satisfiable by phpstan/phpdoc-parser[0.3.5, 0.4.0, 0.4.1, 0.4.2].
    - Can only install one of: phpstan/phpdoc-parser[0.3.5, 0.4.3].
    - Can only install one of: phpstan/phpdoc-parser[0.4.0, 0.4.3].
    - Can only install one of: phpstan/phpdoc-parser[0.4.1, 0.4.3].
    - Can only install one of: phpstan/phpdoc-parser[0.4.2, 0.4.3].
    - Installation request for phpstan/phpdoc-parser (locked at 0.4.3) -> satisfiable by phpstan/phpdoc-parser[0.4.3].
    - Installation request for cakephp/cakephp-codesniffer ^4.1 -> satisfiable by cakephp/cakephp-codesniffer[4.1.0].
    - Conclusion: don't install slevomat/coding-standard 6.2.0|install slevomat/coding-standard 6.0.0|install slevomat/coding-standard 6.0.1|install slevomat/coding-standard 6.0.2|install slevomat/coding-standard 6.0.3|install slevomat/coding-standard 6.0.4|install slevomat/coding-standard 6.0.5|install slevomat/coding-standard 6.0.6|install slevomat/coding-standard 6.0.7|install slevomat/coding-standard 6.0.8|install slevomat/coding-standard 6.1.0|install slevomat/coding-standard 6.1.1
    - Conclusion: remove slevomat/coding-standard 6.2.0|install slevomat/coding-standard 6.0.0|install slevomat/coding-standard 6.0.1|install slevomat/coding-standard 6.0.2|install slevomat/coding-standard 6.0.3|install slevomat/coding-standard 6.0.4|install slevomat/coding-standard 6.0.5|install slevomat/coding-standard 6.0.6|install slevomat/coding-standard 6.0.7|install slevomat/coding-standard 6.0.8|install slevomat/coding-standard 6.1.0|install slevomat/coding-standard 6.1.1
    - cakephp/cakephp-codesniffer 4.1.0 requires slevomat/coding-standard >=6.0 <6.2 -> satisfiable by slevomat/coding-standard[6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5].
    - Can only install one of: slevomat/coding-standard[6.1.2, 6.2.0].
    - Can only install one of: slevomat/coding-standard[6.1.3, 6.2.0].
    - Can only install one of: slevomat/coding-standard[6.1.4, 6.2.0].
    - Can only install one of: slevomat/coding-standard[6.1.5, 6.2.0].
    - Installation request for slevomat/coding-standard (locked at 6.2.0) -> satisfiable by slevomat/coding-standard[6.2.0].


Installation failed, reverting ./composer.json to its original content.
```



composer.json
```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=7.2",
        "cakephp/cakephp": "^4.0",
        "cakephp/migrations": "^3.0",
        "cakephp/plugin-installer": "^1.2",
        "mobiledetect/mobiledetectlib": "^2.8"
    },
    "require-dev": {
        "cakephp/bake": "^2.0.3",
        "cakephp/cakephp-codesniffer": "~4.0.0",
        "cakephp/debug_kit": "^4.0",
        "josegonzalez/dotenv": "^3.2",
        "phpunit/phpunit": "^8.5",
        "psy/psysh": "@stable"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan/Psalm compatibility.",
        "phpstan/phpstan": "PHPStan focuses on finding errors in your code without actually running it. It catches whole classes of bugs even before you write tests for the code."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests/",
            "Cake\\Test\\": "vendor/cakephp/cakephp/tests/"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/",
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/",
        "stan": "phpstan analyse src/",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    },
    "minimum-stability": "dev"
}
```

**Comment by othercorey** [comment]
There is an issue with cakephp-codesniffer downgrading slevomat/coding-standard to < 6.2.0.

composer is rejecting this for some reason.

**Comment by ADmad** [comment]
composer.json already has `"cakephp/cakephp-codesniffer": "~4.0.0"`. So first remove cakephp/cakephp-codesniffer and then requiring it again.

**Comment by othercorey** [comment]
I thought composer would support requiring a new version, but it seems it fails to downgrade previous dependencies.

**Comment by ADmad** [comment]
Yeah sometimes composer gets crazy with dependencies.

**Comment by othercorey** [comment]
I verified cakephp/app can require cakephp/cakephp-codesniffer 4.1.0 so I'm closing this.
