### ISSUE TITLE
Do not allow to use underscore prefixes

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp-codesniffer#312]
```
   <!--
    Property and method names with underscore prefix are allowed in CakePHP.
    Not using underscore prefix is a recommendation of PSR2, not a requirement.
    -->
```
https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/ruleset.xml#L34-L37

But PSR-12 that is used by above mentioned ruleset.xml states:
> Method names MUST NOT be prefixed with a single underscore to indicate protected or private visibility. That is, an underscore prefix explicitly has no meaning.

https://www.php-fig.org/psr/psr-12/#44-methods-and-functions

So, it is not a recommendation but a requirement in PSR-12.

**Comment by ADmad** [comment]
We have ignored PSR-12 rules which don't suite us. There are still lot of protected methods/props which use underscore prefix and 4.0 release before PSR-12 was finalized.
