### ISSUE TITLE
Error SlevoodingStandard.Arrays.TrailingAmatCrrayComma

### ISSUE THREAD

**Issue by lrnzfrr** [cakephp/cakephp-codesniffer#313]
I've been installed the standard in phpcs but if i try :
phpcs --standard=CakePHP src/Controller
i get 
ERROR: Referenced sniff "SlevoodingStandard.Arrays.TrailingAmatCrrayComma" does not exist

**Comment by garas** [comment]
Your install is somehow broken. Rule name should be `SlevomatCodingStandard.Arrays.TrailingArrayComma`.

https://github.com/cakephp/cakephp-codesniffer/blob/4.2.0/CakePHP/ruleset.xml#L132

**Comment by dereuromark** [comment]
Also, if you install it through composer, it will make sure the required dependencies will be installed just fine: https://github.com/cakephp/cakephp-codesniffer/blob/4.2.0/composer.json#L22

**Comment by lrnzfrr** [comment]
> Your install is somehow broken. Rule name should be `SlevomatCodingStandard.Arrays.TrailingArrayComma`.
> 
> https://github.com/cakephp/cakephp-codesniffer/blob/4.2.0/CakePHP/ruleset.xml#L132

sorry my digit error:
ERROR: Referenced sniff "SlevomatCodingStandard.Arrays.TrailingArrayComma"  does not exist

**Comment by lrnzfrr** [comment]
> Also, if you install it through composer, it will make sure the required dependencies will be installed just fine: https://github.com/cakephp/cakephp-codesniffer/blob/4.2.0/composer.json#L22

yes i used composer.

**Comment by dereuromark** [comment]
What version of slevomat/coding-standard was installed?

**Comment by lrnzfrr** [comment]
> What version of slevomat/coding-standard was installed?

if i launch composer inside cakephp-codesniffer : 
slevomat/coding-standard (6.3.8): Loading from cache

**Comment by dereuromark** [comment]
No, inside your project. It requires to be there inside your projects vendor folder directly.

**Comment by lrnzfrr** [comment]
ok if i use phpcs inside project with installed paths everthing works!:
vendor/bin/phpcs ....
But my idea was setup cakephp standard in /usr/bin/phpcs

**Comment by dereuromark** [comment]
Then you need some additional config on your side. But this is then only a documentation issue here.
We might want to add some tips here.

**Comment by lrnzfrr** [comment]
> Then you need some additional config on your side. But this is then only a documentation issue here.
> We might want to add some tips here.

thanks!
