### ISSUE TITLE
Add an empty line between opening tag and declare

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp-codesniffer#314]
According to PSR-12:
> The header of a PHP file may consist of a number of different blocks. If present, each of the blocks below MUST be separated by a single blank line, and MUST NOT contain a blank line. Each block MUST be in the order listed below, although blocks that are not relevant may be omitted.
> 
> * Opening <?php tag.
> * File-level docblock.
> * One or more declare statements.
> ...

https://www.php-fig.org/psr/psr-12/

And an example from there:
```
<?php

/**
 * This file contains an example of coding styles.
 */

declare(strict_types=1);

namespace Vendor\Package;
```

I suggest to change `<property name="newlinesCountBetweenOpenTagAndDeclare" value="1" />` to `<property name="newlinesCountBetweenOpenTagAndDeclare" value="2" />` in order to enforce an empty line to be present after PHP opening tag.

**Comment by dereuromark** [comment]
We deliberately didn't put that extra whitespace in, as we feel like this is just too much noise for nothing.
I would even like to have it on the same line
```
<?php declare(strict_types=1);

/**
```
As everything else is noise and not very useful for devs.

Overall we tried to be as close to it as possible given all pros and cons.

**Comment by ADmad** [comment]
You can just override the rules as per your liking through `phpcs.xml` file in your app root.
