### ISSUE TITLE
PhpStorm

### ISSUE THREAD

**Issue by mcube27** [cakephp/cakephp-codesniffer#337]
We are a team using PHPStorm.

We'd like to be able to reformat using cakephp-codesniffer on save. For now, we use the reformat file on save, but it does not match the cakephp ruleset.

Is there a way to make all of this in a config file ? Or do you know where to configure phpStorm to save using cakephp-codesniffer style set ?

Thnaks a lot

**Comment by othercorey** [comment]
Sorry, not familiar with phpstorm and phpcs.
