### ISSUE TITLE
Constructor property promotion 

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp-codesniffer#367]
Doing something like
```
class MyClass
{
    public function __construct(
        private MyHelper $myHelper
    ) {
        $this->myHelper = $myHelper;
    }
}
```
does not result in a warning/error because doing
```
$this->myHelper = $myHelper;
```
is redundant when using [Constructor property promotion](https://stitcher.io/blog/constructor-promotion-in-php-8)

**Comment by ADmad** [comment]
The check you expect falls within the purview of static code analyzers, not a code formatter.

**Comment by dereuromark** [comment]
At the very least it would be quite tricky for CS rules to detect this fully, since the assignment could be in any order and line within the body - so it would be not a trivial rule to write.

**Comment by LordSimal** [comment]
I have created separate issues for PHPStan and Psalm. Thanks for the info 👍🏻
