### ISSUE TITLE
Cake 5 CS

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp-codesniffer#368]
I see that current Cake5 sniffer version is still 7.2+
It seems to work with union types and other PHP 8+ topics, but still is PHP 7

Is there any plan to make the new major that is working with Cake5 and PHP 8 also tailored for it?
Or will it also be suitable for previous Cake versions etc?

I am asking, because if we tailor it to PHP 8+, we can also further include specific 8+ enhancements, e.g.
```xml
    <rule ref="SlevomatCodingStandard.Functions.RequireTrailingCommaInDeclaration"/>
    <rule ref="SlevomatCodingStandard.Functions.RequireTrailingCommaInClosureUse"/>
```
which improve diffing

Amonst a few other sniffs.

**Comment by ADmad** [comment]
Probably an oversight, v5 of the code-sniffer should be PHP 8.1+.

**Comment by dereuromark** [comment]
PR open now.
