### ISSUE TITLE
can support for slevomat/coding-standard v6 be removed?

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp-codesniffer#382]
https://github.com/cakephp/cakephp-codesniffer/blob/fba3e43855e39246c6ab3f61da97af09f9d80341/CakePHP/ruleset.xml#L157

the ruleset config adds configuration entries that no longer exist in current versions of slevomat/conding-standard leading to deprecations in PHP 8.2

Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff::$newlinesCountAfterDeclare is deprecated

Is slevomat/coding-standard v6 support still required ? v8 covers [PHP 7.2 - PHP 8.2](php: ^7.2 || ^8.0) and should be fine for projects running CakePHP 4?

ref: https://github.com/squizlabs/PHP_CodeSniffer/pull/3629#issuecomment-1500485945

**Comment by othercorey** [comment]
I reproduced this. Looks like we need to bump the minimum slevomat in a new minor and drop old configs.

**Comment by othercorey** [comment]
Are you seeing any errors beyond the warning?

**Comment by swiffer** [comment]
No, otherwise working Just fine. (The warning leads to phpcs Not working in vscode / Run on save in my dev env - that's my Driver for getting this fixed)

**Comment by ADmad** [comment]
> The warning leads to phpcs Not working in vscode..

That's bad for usability.

@othercorey I guess we should just keep v8 of slevomat CS and do a new minor for our 4.x.

**Comment by othercorey** [comment]
Dropped in 4.7.0 release.
