### ISSUE TITLE
1.x FunctionCommentThrowTagSniff

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp-codesniffer#96]
While doing some CS fixes in our code, I came accross `FunctionCommentThrowTagSniff.php`.

https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/Sniffs/Commenting/FunctionCommentThrowTagSniff.php

There is also an identically named sniff in the Squiz Standard:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php

It seems @jrbasso contributed it to support namespaces
https://github.com/cakephp/cakephp-codesniffer/commit/86edcb83e243352dbc52172db966dc29fe3f4b21

> Implemented sniff to validate `@throws` in PHPDoc with support to nameespaces

But it seems there is a probably related commit to the original Sniff around that time, too:
https://github.com/squizlabs/PHP_CodeSniffer/commit/add2da9f2e0057c2d3fc14dc3f98b83cb3f4f48a

Commit history for CakePHP's FunctionCommentThrowTagSniff.php
https://github.com/cakephp/cakephp-codesniffer/commits/ea8568edb5f2f7eaf0f536372f677de365b5d7c3/Sniffs/Commenting/FunctionCommentThrowTagSniff.php
https://github.com/cakephp/cakephp-codesniffer/commits/master/CakePHP/Sniffs/Commenting/FunctionCommentThrowTagSniff.php

Commit history for the original FunctionCommentThrowTagSniff.php
https://github.com/squizlabs/PHP_CodeSniffer/commits/master/CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php

I haven't tried it yet, but couldn't we replace @jrbasso 's sniff with the original one?
May be @jrbasso can shed some light on this.

I'm asking because I also found a bug that exist in both sniffs. ;-)

**Comment by ravage84** [comment]
@ADmad this ticket was opened towards 1.x, please re-open.

**Comment by ADmad** [comment]
@ravage84 You can open a pull request if you think this is worth pursing.

**Comment by ravage84** [comment]
May be I will but that does not change the (open) state ot the issue for 1.x

**Comment by ADmad** [comment]
It's normal practice to close tickets which remain idle for a long period and are unlikely to be acted upon. 

Replacing the sniff with original one from Squiz is a pretty low priority task. You did mention finding a bug but haven't provided any details about it.
